spring.datasource.url=jdbc:h2:file:./data/festivaldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:data.sql
spring.h2.console.enabled=true
spring.h2.console.path=/h2
